import { Product } from '@/model/Product';

// Mock product data
const products: Product[] = [
    {
        id: 'prod-1',
        name: 'Apple Watch Series 7',
        description: 'The latest Apple Watch with advanced health features including blood oxygen monitoring, ECG, and sleep tracking. Water resistant with a larger, always-on Retina display that is easy to read in any light. Available in multiple colors and band options to match your style.',
        price: 399.99,
        priceRange: '$$$',
        rating: 4.8,
        imageUrl: 'https://example.com/apple-watch.jpg',
        affiliateLink: 'https://amazon.com/product/123',
        relatedGiftIds: ['gift-1'],
        tags: ['Technology', 'Wearables', 'Health']
    },
    {
        id: 'prod-2',
        name: 'Weighted Blanket',
        description: 'Premium weighted blanket for better sleep and relaxation. The gentle pressure helps reduce anxiety and improve sleep quality. Made with high-quality, breathable materials that keep you comfortable all night long. Available in different weights and sizes to suit your needs.',
        price: 89.99,
        priceRange: '$$',
        rating: 4.6,
        imageUrl: 'https://example.com/blanket.jpg',
        affiliateLink: 'https://amazon.com/product/456',
        relatedGiftIds: ['gift-2'],
        tags: ['Home', 'Comfort', 'Sleep']
    },
    {
        id: 'prod-3',
        name: 'Gourmet Chocolate Box',
        description: 'Assorted gourmet chocolates in an elegant gift box. Perfect for special occasions or as a thoughtful gift. Each chocolate is handcrafted with premium ingredients and presented in a beautiful box suitable for gifting.',
        price: 45.99,
        priceRange: '$$',
        rating: 4.5,
        imageUrl: 'https://example.com/chocolate.jpg',
        affiliateLink: 'https://amazon.com/product/789',
        relatedGiftIds: ['gift-3'],
        tags: ['Food', 'Sweets', 'Gift']
    },
    {
        id: 'prod-4',
        name: 'Crystal Whiskey Decanter Set',
        description: 'Elegant lead-free crystal decanter with four matching whiskey glasses. The set features a timeless design that adds sophistication to any home bar. The decanter has an airtight seal to preserve your favorite spirits.',
        price: 129.99,
        priceRange: '$$$',
        rating: 4.7,
        imageUrl: 'https://example.com/decanter.jpg',
        affiliateLink: 'https://amazon.com/product/101',
        relatedGiftIds: ['gift-4'],
        tags: ['Home', 'Luxury', 'Barware']
    },
    {
        id: 'prod-5',
        name: 'Aromatherapy Diffuser Set',
        description: 'Modern ultrasonic diffuser with color-changing LED lights and 10 essential oils. Creates a soothing atmosphere with gentle mist and natural scents. Auto shut-off feature for safety and multiple mist settings for customized use.',
        price: 59.99,
        priceRange: '$$',
        rating: 4.4,
        imageUrl: 'https://example.com/diffuser.jpg',
        affiliateLink: 'https://amazon.com/product/202',
        relatedGiftIds: ['gift-5'],
        tags: ['Wellness', 'Home', 'Relaxation']
    },
    {
        id: 'prod-6',
        name: 'Premium Fitness Tracker',
        description: 'Advanced fitness tracker with heart rate monitoring, sleep analysis, and 20+ exercise modes. Waterproof design with a bright color display and up to 7 days of battery life. Connects to your smartphone for notifications and GPS tracking.',
        price: 79.99,
        priceRange: '$$',
        rating: 4.6,
        imageUrl: 'https://example.com/fitness-tracker.jpg',
        affiliateLink: 'https://amazon.com/product/303',
        relatedGiftIds: ['gift-6'],
        tags: ['Technology', 'Fitness', 'Health']
    },
    {
        id: 'prod-7',
        name: 'Next-Gen Gaming Console',
        description: 'The latest gaming console featuring 4K gaming, fast load times, and an extensive game library. Includes a wireless controller, HDMI cable, and digital game download. Stream your favorite entertainment apps in crisp 4K resolution.',
        price: 499.99,
        priceRange: '$$$',
        rating: 4.9,
        imageUrl: 'https://example.com/gaming-console.jpg',
        affiliateLink: 'https://amazon.com/product/404',
        relatedGiftIds: ['gift-7'],
        tags: ['Technology', 'Entertainment', 'Gaming']
    },
    {
        id: 'prod-8',
        name: 'Noise-Cancelling Headphones',
        description: 'Premium wireless headphones with industry-leading noise cancellation technology. Features include touch controls, voice assistant access, and up to 30 hours of battery life. Foldable design with plush ear cushions for ultimate comfort.',
        price: 299.99,
        priceRange: '$$$',
        rating: 4.8,
        imageUrl: 'https://example.com/headphones.jpg',
        affiliateLink: 'https://amazon.com/product/505',
        relatedGiftIds: ['gift-8'],
        tags: ['Technology', 'Music', 'Audio']
    },
    {
        id: 'prod-9',
        name: 'Indoor Plant Starter Kit',
        description: 'Collection of 5 easy-care indoor plants with decorative pots and care instructions. Perfect for beginners or plant enthusiasts. Includes succulents, air plants, and small tropical varieties chosen for their adaptability and beauty.',
        price: 64.99,
        priceRange: '$$',
        rating: 4.5,
        imageUrl: 'https://example.com/indoor-plants.jpg',
        affiliateLink: 'https://amazon.com/product/606',
        relatedGiftIds: ['gift-9'],
        tags: ['Home', 'Nature', 'Decor']
    },
    {
        id: 'prod-10',
        name: 'Antique-Style Jewelry Box',
        description: 'Handcrafted wooden jewelry box with vintage-inspired design. Features multiple drawers, ring rolls, and a lined interior. The lock and key ensure your valuables stay secure and the mirror inside makes it practical for daily use.',
        price: 79.99,
        priceRange: '$$',
        rating: 4.7,
        imageUrl: 'https://example.com/jewelry-box.jpg',
        affiliateLink: 'https://amazon.com/product/707',
        relatedGiftIds: ['gift-10'],
        tags: ['Accessories', 'Storage', 'Home']
    },
    {
        id: 'prod-11',
        name: 'Gourmet Kitchen Gadget Collection',
        description: 'Set of 12 innovative kitchen tools designed to simplify cooking tasks. Includes specialty peelers, precision slicers, and multi-functional utensils. Dishwasher-safe and ergonomically designed for comfort and efficiency.',
        price: 69.99,
        priceRange: '$$',
        rating: 4.4,
        imageUrl: 'https://example.com/kitchen-gadgets.jpg',
        affiliateLink: 'https://amazon.com/product/808',
        relatedGiftIds: ['gift-11'],
        tags: ['Kitchen', 'Practical', 'Cooking']
    },
    {
        id: 'prod-12',
        name: 'Full-Grain Leather Wallet',
        description: 'Premium full-grain leather wallet with RFID blocking technology. Features 8 card slots, 2 bill compartments, and ID window. The slim design fits comfortably in front or back pockets and develops a beautiful patina over time.',
        price: 59.99,
        priceRange: '$$',
        rating: 4.8,
        imageUrl: 'https://example.com/leather-wallet.jpg',
        affiliateLink: 'https://amazon.com/product/909',
        relatedGiftIds: ['gift-12'],
        tags: ['Accessories', 'Fashion', 'Practical']
    },
    {
        id: 'prod-13',
        name: 'Professional Massage Gun',
        description: 'High-powered percussion massage device with 6 interchangeable heads and 20 speed settings. Provides deep tissue massage for muscle recovery and pain relief. Quiet operation with 6-hour battery life and carrying case included.',
        price: 159.99,
        priceRange: '$$$',
        rating: 4.7,
        imageUrl: 'https://example.com/massage-gun.jpg',
        affiliateLink: 'https://amazon.com/product/1010',
        relatedGiftIds: ['gift-13'],
        tags: ['Wellness', 'Fitness', 'Recovery']
    },
    {
        id: 'prod-14',
        name: 'Sterling Silver Heart Pendant',
        description: 'Elegant sterling silver heart pendant on an 18-inch chain. The delicate design features cubic zirconia accents that catch the light beautifully. Comes in a gift box with a special message card for your loved one.',
        price: 129.99,
        priceRange: '$$$',
        rating: 4.9,
        imageUrl: 'https://example.com/necklace.jpg',
        affiliateLink: 'https://amazon.com/product/1111',
        relatedGiftIds: ['gift-14'],
        tags: ['Jewelry', 'Fashion', 'Romantic']
    },
    {
        id: 'prod-15',
        name: 'Portable Outdoor Pizza Oven',
        description: 'Compact outdoor pizza oven that reaches 950°F for authentic Neapolitan-style pizza in just 60 seconds. Runs on propane with easy ignition and temperature control. Portable design makes it perfect for backyard gatherings, camping, or tailgating.',
        price: 349.99,
        priceRange: '$$$',
        rating: 4.8,
        imageUrl: 'https://example.com/pizza-oven.jpg',
        affiliateLink: 'https://amazon.com/product/1212',
        relatedGiftIds: ['gift-15'],
        tags: ['Kitchen', 'Outdoor', 'Cooking']
    },
    {
        id: 'prod-16',
        name: 'Instant Film Camera',
        description: 'Retro-inspired instant camera that prints credit-card sized photos instantly. Features include selfie mirror, automatic flash, and double exposure mode. Compact design makes it perfect for parties, travel, and everyday memories.',
        price: 99.99,
        priceRange: '$$',
        rating: 4.5,
        imageUrl: 'https://example.com/polaroid.jpg',
        affiliateLink: 'https://amazon.com/product/1313',
        relatedGiftIds: ['gift-16'],
        tags: ['Technology', 'Photography', 'Creative']
    },
    {
        id: 'prod-17',
        name: 'Handmade Patchwork Quilt',
        description: 'Artisanal cotton patchwork quilt made with traditional techniques. The queen-size blanket features a beautiful pattern in complementary colors. Machine washable and designed to last for generations as a cherished heirloom.',
        price: 189.99,
        priceRange: '$$',
        rating: 4.7,
        imageUrl: 'https://example.com/quilt.jpg',
        affiliateLink: 'https://amazon.com/product/1414',
        relatedGiftIds: ['gift-17'],
        tags: ['Home', 'Handmade', 'Bedding']
    },
    {
        id: 'prod-18',
        name: 'Bluetooth Turntable',
        description: 'Modern record player with vintage aesthetic and Bluetooth connectivity. Plays 33/45/78 RPM records with built-in speakers or connects to external audio systems. Includes USB port for digitizing your vinyl collection.',
        price: 199.99,
        priceRange: '$$$',
        rating: 4.6,
        imageUrl: 'https://example.com/record-player.jpg',
        affiliateLink: 'https://amazon.com/product/1515',
        relatedGiftIds: ['gift-18'],
        tags: ['Music', 'Technology', 'Entertainment']
    },
    {
        id: 'prod-19',
        name: 'Premium Smartwatch',
        description: 'Advanced smartwatch with always-on display, health monitoring, and smartphone notifications. Features include GPS tracking, waterproof design, and customizable watch faces. Battery lasts up to 5 days on a single charge.',
        price: 279.99,
        priceRange: '$$$',
        rating: 4.7,
        imageUrl: 'https://example.com/smartwatch.jpg',
        affiliateLink: 'https://amazon.com/product/1616',
        relatedGiftIds: ['gift-19'],
        tags: ['Technology', 'Fitness', 'Wearables']
    },
    {
        id: 'prod-20',
        name: 'Travel Backpack with USB Charger',
        description: 'Water-resistant backpack with built-in USB charging port and anti-theft features. Includes multiple compartments, laptop sleeve, and luggage strap. The ergonomic design provides comfort during long trips and commutes.',
        price: 79.99,
        priceRange: '$$',
        rating: 4.6,
        imageUrl: 'https://example.com/travel-backpack.jpg',
        affiliateLink: 'https://amazon.com/product/1717',
        relatedGiftIds: ['gift-20'],
        tags: ['Travel', 'Accessories', 'Practical']
    },
    {
        id: 'prod-21',
        name: 'Windproof Automatic Umbrella',
        description: 'Premium umbrella with automatic open/close function and windproof design. The fiberglass frame prevents inversion in strong gusts and the water-repellent fabric dries quickly. Includes a sleek carrying case and wrist strap.',
        price: 29.99,
        priceRange: '$',
        rating: 4.5,
        imageUrl: 'https://example.com/umbrella.jpg',
        affiliateLink: 'https://amazon.com/product/1818',
        relatedGiftIds: ['gift-21'],
        tags: ['Accessories', 'Practical', 'Weather']
    },
    {
        id: 'prod-22',
        name: 'Virtual Reality Gaming Headset',
        description: 'Immersive VR headset with high-resolution display and precise motion tracking. Includes two wireless controllers and access to a vast library of games and experiences. The adjustable headstrap and cushioned faceplate ensure comfortable extended use.',
        price: 399.99,
        priceRange: '$$$',
        rating: 4.8,
        imageUrl: 'https://example.com/vr-headset.jpg',
        affiliateLink: 'https://amazon.com/product/1919',
        relatedGiftIds: ['gift-22'],
        tags: ['Technology', 'Entertainment', 'Gaming']
    },
    {
        id: 'prod-23',
        name: 'Premium Wireless Earbuds',
        description: 'High-fidelity wireless earbuds with active noise cancellation and transparency mode. Features include touch controls, voice assistant support, and sweat resistance. The charging case provides up to 24 hours of battery life.',
        price: 149.99,
        priceRange: '$$',
        rating: 4.7,
        imageUrl: 'https://example.com/wireless-earbuds.jpg',
        affiliateLink: 'https://amazon.com/product/2020',
        relatedGiftIds: ['gift-23'],
        tags: ['Technology', 'Music', 'Audio']
    },
    {
        id: 'prod-24',
        name: 'Xbox Digital Gift Card',
        description: 'Digital gift card for the Xbox store that can be redeemed for games, add-ons, movies, TV shows, and apps. Available in multiple denominations and delivered instantly via email. Never expires and has no fees.',
        price: 50.00,
        priceRange: '$$',
        rating: 4.9,
        imageUrl: 'https://example.com/xbox-card.jpg',
        affiliateLink: 'https://amazon.com/product/2121',
        relatedGiftIds: ['gift-24'],
        tags: ['Gaming', 'Digital', 'Entertainment']
    },
    {
        id: 'prod-25',
        name: 'Eco-Friendly Yoga Mat',
        description: 'Premium yoga mat made from sustainable, non-toxic materials. Features excellent grip, cushioning, and alignment markers for proper form. Includes carrying strap and comes in a variety of calming colors.',
        price: 39.99,
        priceRange: '$',
        rating: 4.6,
        imageUrl: 'https://example.com/yoga-mat.jpg',
        affiliateLink: 'https://amazon.com/product/2222',
        relatedGiftIds: ['gift-25'],
        tags: ['Fitness', 'Wellness', 'Eco-Friendly']
    },
    {
        id: 'prod-26',
        name: 'Desktop Zen Garden Kit',
        description: 'Miniature desktop zen garden with fine sand, natural rocks, bamboo rake, and ceramic base. The meditative practice of raking patterns promotes mindfulness and stress relief. Makes an elegant addition to any home or office space.',
        price: 24.99,
        priceRange: '$',
        rating: 4.4,
        imageUrl: 'https://example.com/zen-garden.jpg',
        affiliateLink: 'https://amazon.com/product/2323',
        relatedGiftIds: ['gift-26'],
        tags: ['Wellness', 'Decor', 'Mindfulness']
    }
];

export default products; 